# Generated by Django 6.0.2 on 2026-02-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='accounts_users', related_query_name='accounts_user', to='accounts.role'),
        ),
    ]
