# Generated by Django 6.0 on 2026-02-12 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalevidence',
            name='coroner_approved',
            field=models.BooleanField(default=False, verbose_name='Coroner Approved'),
        ),
        migrations.AddField(
            model_name='biologicalevidence',
            name='coroner_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Coroner Approval Date'),
        ),
        migrations.AddField(
            model_name='biologicalevidence',
            name='coroner_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coroner_approved_evidence', to=settings.AUTH_USER_MODEL, verbose_name='Approved By (Coroner)'),
        ),
        migrations.AddField(
            model_name='biologicalevidence',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='documentevidence',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='otherevidence',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='vehicleevidence',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='witnesstestimony',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='biologicalevidence',
            name='lab_results',
            field=models.TextField(blank=True, verbose_name='Lab Results / Follow-up Result'),
        ),
        migrations.CreateModel(
            name='DetectiveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING_SERGEANT', 'Pending Sergeant Review'), ('APPROVED', 'Approved'), ('DISAGREEMENT', 'Disagreement')], default='PENDING_SERGEANT', max_length=20, verbose_name='Status')),
                ('sergeant_message', models.TextField(blank=True, verbose_name='Sergeant Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detective_reports', to='core.case', verbose_name='Case')),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_detective_reports', to=settings.AUTH_USER_MODEL, verbose_name='Detective')),
                ('sergeant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detective_reports', to=settings.AUTH_USER_MODEL, verbose_name='Sergeant')),
            ],
            options={
                'verbose_name': 'Detective Report',
                'verbose_name_plural': 'Detective Reports',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['case'], name='core_detect_case_id_368704_idx'), models.Index(fields=['status'], name='core_detect_status_0ef81a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_object_id', models.PositiveIntegerField()),
                ('to_object_id', models.PositiveIntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='core.case', verbose_name='Case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence_links', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links_from', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links_to', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Evidence Link',
                'verbose_name_plural': 'Evidence Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case'], name='core_eviden_case_id_2fde6d_idx'), models.Index(fields=['from_content_type', 'from_object_id'], name='core_eviden_from_co_47a369_idx'), models.Index(fields=['to_content_type', 'to_object_id'], name='core_eviden_to_cont_b77466_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='Message')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.case', verbose_name='Case')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='core_notifi_recipie_9d58cb_idx'), models.Index(fields=['case'], name='core_notifi_case_id_5821ed_idx'), models.Index(fields=['read_at'], name='core_notifi_read_at_3d6d6f_idx')],
            },
        ),
    ]
