# Generated by Django 6.0 on 2026-02-12 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evidence_title_case_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='officer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Officer Reviewed At'),
        ),
        migrations.AddField(
            model_name='reward',
            name='officer_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_officer_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Officer Reviewed By'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_DETECTIVE', 'Pending Detective Review'), ('APPROVED', 'Approved'), ('READY_FOR_PAYMENT', 'Ready for Payment'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='teamreward',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_DETECTIVE', 'Pending Detective Review'), ('APPROVED', 'Approved'), ('READY_FOR_PAYMENT', 'Ready for Payment'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
