# Generated by Django 6.0 on 2026-02-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_case_lifecycle'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interrogation',
            name='core_interr_suspect_77f298_idx',
        ),
        migrations.RemoveIndex(
            model_name='interrogation',
            name='core_interr_status_b1bd9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='interrogation',
            name='core_interr_detecti_3cc953_idx',
        ),
        migrations.RemoveIndex(
            model_name='interrogation',
            name='core_interr_sergean_7092ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='suspect',
            name='core_suspec_nationa_b1be2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='suspect',
            name='core_suspec_status_1d4d8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='suspect',
            name='core_suspec_is_want_ad8e55_idx',
        ),
        migrations.RemoveIndex(
            model_name='suspect',
            name='core_suspec_last_na_73068e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='suspectcaselink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='suspectcaselink',
            name='suspect',
        ),
        migrations.RemoveField(
            model_name='suspectcaselink',
            name='case',
        ),
        migrations.RemoveIndex(
            model_name='trial',
            name='core_trial_status_c7343d_idx',
        ),
        migrations.RemoveIndex(
            model_name='trial',
            name='core_trial_schedul_ce3ae9_idx',
        ),
        migrations.RemoveIndex(
            model_name='trial',
            name='core_trial_created_ba1fcc_idx',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='cases',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='case',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='judge',
        ),
        migrations.DeleteModel(
            name='Interrogation',
        ),
        migrations.DeleteModel(
            name='Suspect',
        ),
        migrations.DeleteModel(
            name='SuspectCaseLink',
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
