# Generated by Django 6.0 on 2026-02-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_suspect_trial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reward',
            name='core_reward_status_bb1b17_idx',
        ),
        migrations.RemoveIndex(
            model_name='reward',
            name='core_reward_recipie_50f10d_idx',
        ),
        migrations.RemoveIndex(
            model_name='reward',
            name='core_reward_case_id_d89cf1_idx',
        ),
        migrations.RemoveIndex(
            model_name='reward',
            name='core_reward_reward__912f85_idx',
        ),
        migrations.RemoveIndex(
            model_name='reward',
            name='core_reward_is_civi_fc4747_idx',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='case',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='officer_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='TeamReward',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
