# Generated by Django 6.0 on 2026-02-13 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suspectcaselink',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspect_case_opinions', to=settings.AUTH_USER_MODEL, verbose_name='Captain'),
        ),
        migrations.AddField(
            model_name='suspectcaselink',
            name='captain_opinion',
            field=models.TextField(blank=True, help_text="Captain's final opinion with statements, documents, and scores", verbose_name='Captain Final Opinion'),
        ),
        migrations.AddField(
            model_name='suspectcaselink',
            name='captain_opinion_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Captain Opinion Date'),
        ),
        migrations.AddField(
            model_name='suspectcaselink',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspect_case_chief_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Police Chief'),
        ),
        migrations.AddField(
            model_name='suspectcaselink',
            name='chief_approval_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chief Approval Date'),
        ),
        migrations.AddField(
            model_name='suspectcaselink',
            name='chief_approved',
            field=models.BooleanField(blank=True, help_text='True=approved, False=rejected; null=pending or not required (non-critical)', null=True, verbose_name='Chief Approved'),
        ),
    ]
