# Re-export from accounts so existing imports (from core.permissions import ...) keep working.
from accounts.permissions import (
    HasRole,
    HasPermission,
    HasAnyRole,
    IsSystemAdmin,
    IsPoliceChief,
    IsCaptain,
    IsSergeant,
    IsDetective,
    IsPoliceOfficer,
    IsCadet,
    IsCoroner,
    IsJudge,
    IsComplainant,
    IsOfficer,
    IsCadetOrOfficer,
    IsPoliceRankExceptCadet,
    IsDetectiveOrSergeantOrChief,
    IsSergeantOrCaptainOrChief,
)

__all__ = [
    'HasRole',
    'HasPermission',
    'HasAnyRole',
    'IsSystemAdmin',
    'IsPoliceChief',
    'IsCaptain',
    'IsSergeant',
    'IsDetective',
    'IsPoliceOfficer',
    'IsCadet',
    'IsCoroner',
    'IsJudge',
    'IsComplainant',
    'IsOfficer',
    'IsCadetOrOfficer',
    'IsPoliceRankExceptCadet',
    'IsDetectiveOrSergeantOrChief',
    'IsSergeantOrCaptainOrChief',
]
