# Generated by Django 6.0 on 2026-02-13 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('national_id', models.CharField(help_text='10-digit national identification number', max_length=10, unique=True, verbose_name='National ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='suspects/photos/', verbose_name='Photo')),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('DETAINED', 'Detained'), ('RELEASED', 'Released'), ('CHARGED', 'Charged'), ('CONVICTED', 'Convicted'), ('ACQUITTED', 'Acquitted'), ('FUGITIVE', 'Fugitive')], default='IDENTIFIED', max_length=30, verbose_name='Status')),
                ('is_wanted', models.BooleanField(default=False, help_text='True if suspect is actively wanted', verbose_name='Is Wanted')),
                ('pursuit_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Pursuit Start Date')),
                ('capture_date', models.DateTimeField(blank=True, null=True, verbose_name='Capture Date')),
                ('detention_location', models.CharField(blank=True, max_length=200, verbose_name='Detention Location')),
                ('detention_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Detention Start Date')),
                ('detention_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Detention End Date')),
                ('bail_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bail Amount')),
                ('bail_paid', models.BooleanField(default=False, verbose_name='Bail Paid')),
                ('bail_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Bail Payment Date')),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fine Amount')),
                ('fine_paid', models.BooleanField(default=False, verbose_name='Fine Paid')),
                ('fine_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fine Payment Date')),
                ('criminal_history', models.TextField(blank=True, verbose_name='Criminal History')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Suspect',
                'verbose_name_plural': 'Suspects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspectCaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detective_guilt_score', models.IntegerField(blank=True, help_text="Detective's assessment of guilt probability (1-10)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Detective Guilt Score')),
                ('sergeant_guilt_score', models.IntegerField(blank=True, help_text="Sergeant's assessment of guilt probability (1-10)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Sergeant Guilt Score')),
                ('detective_assessment_date', models.DateTimeField(blank=True, null=True, verbose_name='Detective Assessment Date')),
                ('sergeant_assessment_date', models.DateTimeField(blank=True, null=True, verbose_name='Sergeant Assessment Date')),
                ('role_in_crime', models.CharField(blank=True, help_text='Suspected role in this specific crime', max_length=200, verbose_name='Role in Crime')),
                ('identification_method', models.CharField(blank=True, help_text='How suspect was identified', max_length=200, verbose_name='Identification Method')),
                ('notes', models.TextField(blank=True, verbose_name='Case-Specific Notes')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspect_links', to='cases.case', verbose_name='Case')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to='investigation.suspect', verbose_name='Suspect')),
            ],
            options={
                'verbose_name': 'Suspect Case Link',
                'verbose_name_plural': 'Suspect Case Links',
                'ordering': ['-created_at'],
                'unique_together': {('suspect', 'case')},
            },
        ),
        migrations.AddField(
            model_name='suspect',
            name='cases',
            field=models.ManyToManyField(related_name='suspects', through='investigation.SuspectCaseLink', to='cases.case', verbose_name='Related Cases'),
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interrogation_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Interrogation Number')),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled Date')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('detective_notes', models.TextField(blank=True, verbose_name='Detective Notes')),
                ('detective_guilt_rating', models.IntegerField(blank=True, help_text='1 = least likely guilty, 10 = most likely guilty', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Detective Guilt Rating')),
                ('detective_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Detective Completed At')),
                ('sergeant_notes', models.TextField(blank=True, verbose_name='Sergeant Notes')),
                ('sergeant_guilt_rating', models.IntegerField(blank=True, help_text='1 = least likely guilty, 10 = most likely guilty', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Sergeant Guilt Rating')),
                ('sergeant_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Sergeant Completed At')),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='interrogations/audio/', verbose_name='Audio Recording')),
                ('video_recording', models.FileField(blank=True, null=True, upload_to='interrogations/video/', verbose_name='Video Recording')),
                ('transcript', models.TextField(blank=True, verbose_name='Transcript')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interrogations_as_detective', to=settings.AUTH_USER_MODEL, verbose_name='Detective')),
                ('sergeant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interrogations_as_sergeant', to=settings.AUTH_USER_MODEL, verbose_name='Sergeant')),
                ('suspect_case_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='investigation.suspectcaselink', verbose_name='Suspect Case Link')),
            ],
            options={
                'verbose_name': 'Interrogation',
                'verbose_name_plural': 'Interrogations',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=20, verbose_name='Trial Status')),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled Date')),
                ('verdict', models.CharField(blank=True, choices=[('GUILTY', 'Guilty'), ('INNOCENT', 'Innocent')], max_length=10, null=True, verbose_name='Verdict')),
                ('punishment', models.TextField(blank=True, verbose_name='Punishment')),
                ('verdict_date', models.DateTimeField(blank=True, null=True, verbose_name='Verdict Date')),
                ('judge_notes', models.TextField(blank=True, verbose_name='Judge Notes')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='cases.case', verbose_name='Case')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presided_trials', to=settings.AUTH_USER_MODEL, verbose_name='Judge')),
            ],
            options={
                'verbose_name': 'Trial',
                'verbose_name_plural': 'Trials',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='DetectiveReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING_SERGEANT', 'Pending Sergeant Review'), ('APPROVED', 'Approved'), ('DISAGREEMENT', 'Disagreement')], default='PENDING_SERGEANT', max_length=20, verbose_name='Status')),
                ('sergeant_message', models.TextField(blank=True, verbose_name='Sergeant Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detective_reports', to='cases.case', verbose_name='Case')),
                ('detective', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_detective_reports', to=settings.AUTH_USER_MODEL, verbose_name='Detective')),
                ('sergeant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_detective_reports', to=settings.AUTH_USER_MODEL, verbose_name='Sergeant')),
            ],
            options={
                'verbose_name': 'Detective Report',
                'verbose_name_plural': 'Detective Reports',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['case'], name='investigati_case_id_d2a8b4_idx'), models.Index(fields=['status'], name='investigati_status_6fe589_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_object_id', models.PositiveIntegerField()),
                ('to_object_id', models.PositiveIntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='cases.case', verbose_name='Case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evidence_links', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('from_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_evidence_links_from', to='contenttypes.contenttype')),
                ('to_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_evidence_links_to', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Evidence Link',
                'verbose_name_plural': 'Evidence Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case'], name='investigati_case_id_3c00cd_idx'), models.Index(fields=['from_content_type', 'from_object_id'], name='investigati_from_co_e964d7_idx'), models.Index(fields=['to_content_type', 'to_object_id'], name='investigati_to_cont_0cdbb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='Message')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case', verbose_name='Case')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='investigati_recipie_20d8db_idx'), models.Index(fields=['case'], name='investigati_case_id_178de1_idx'), models.Index(fields=['read_at'], name='investigati_read_at_5ae4c2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['national_id'], name='investigati_nationa_190001_idx'),
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['status'], name='investigati_status_008e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['is_wanted'], name='investigati_is_want_cf2b39_idx'),
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['last_name', 'first_name'], name='investigati_last_na_1f5825_idx'),
        ),
        migrations.AddIndex(
            model_name='interrogation',
            index=models.Index(fields=['suspect_case_link', '-scheduled_date'], name='investigati_suspect_f5b5f9_idx'),
        ),
        migrations.AddIndex(
            model_name='interrogation',
            index=models.Index(fields=['status'], name='investigati_status_e58b01_idx'),
        ),
        migrations.AddIndex(
            model_name='interrogation',
            index=models.Index(fields=['detective'], name='investigati_detecti_2579d5_idx'),
        ),
        migrations.AddIndex(
            model_name='interrogation',
            index=models.Index(fields=['sergeant'], name='investigati_sergean_e13964_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['status'], name='investigati_status_1fdccc_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['scheduled_date'], name='investigati_schedul_7bf88a_idx'),
        ),
        migrations.AddIndex(
            model_name='trial',
            index=models.Index(fields=['-created_at'], name='investigati_created_608d79_idx'),
        ),
    ]
