# Generated by Django 6.0 on 2026-02-13 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_add_captain_opinion_chief_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect',
            name='bail_amount',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='bail_paid',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='bail_payment_date',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='fine_amount',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='fine_paid',
        ),
        migrations.RemoveField(
            model_name='suspect',
            name='fine_payment_date',
        ),
        migrations.CreateModel(
            name='BailFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bail_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bail Amount')),
                ('bail_paid', models.BooleanField(default=False, verbose_name='Bail Paid')),
                ('bail_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Bail Payment Date')),
                ('bail_payment_reference', models.CharField(blank=True, help_text='Payment gateway transaction reference', max_length=255, verbose_name='Bail Payment Reference')),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fine Amount')),
                ('fine_paid', models.BooleanField(default=False, verbose_name='Fine Paid')),
                ('fine_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fine Payment Date')),
                ('fine_payment_reference', models.CharField(blank=True, help_text='Payment gateway transaction reference', max_length=255, verbose_name='Fine Payment Reference')),
                ('sergeant_approval', models.BooleanField(default=False, help_text='Required for level 3 crimes before release upon payment', verbose_name='Sergeant Approval')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('amount_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bail_fine_amounts_set', to=settings.AUTH_USER_MODEL, verbose_name='Amount Set By')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bail_fine_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('suspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bail_fine', to='investigation.suspect', verbose_name='Suspect')),
            ],
            options={
                'verbose_name': 'Bail / Fine',
                'verbose_name_plural': 'Bail / Fine',
            },
        ),
    ]
