# Generated by Django 4.2.28 on 2026-02-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_add_reportedsuspect_and_message'),
        ('investigation', '0003_bail_fine_model_and_remove_from_suspect'),
    ]

    operations = [
    ]
