# Generated by Django 6.0 on 2026-02-13 18:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_DETECTIVE', 'Pending Detective Review'), ('APPROVED', 'Approved'), ('READY_FOR_PAYMENT', 'Ready for Payment'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('distribution_completed', models.BooleanField(default=False, verbose_name='Distribution Completed')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_rewards_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rewards', to='cases.case', verbose_name='Related Case')),
            ],
            options={
                'verbose_name': 'Team Reward',
                'verbose_name_plural': 'Team Rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Unique Reward Code')),
                ('reward_type', models.CharField(choices=[('CASE_SOLVING', 'Case Solving'), ('INFORMATION_PROVIDED', 'Information Provided'), ('WITNESS_TESTIMONY', 'Witness Testimony'), ('TEAM_BONUS', 'Team Bonus'), ('SPECIAL_ACHIEVEMENT', 'Special Achievement'), ('OVERTIME', 'Overtime'), ('OTHER', 'Other')], default='CASE_SOLVING', max_length=30, verbose_name='Reward Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_DETECTIVE', 'Pending Detective Review'), ('APPROVED', 'Approved'), ('READY_FOR_PAYMENT', 'Ready for Payment'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('information_submitted', models.TextField(blank=True, help_text='Details of information provided by civilian', verbose_name='Information Submitted')),
                ('is_civilian_reward', models.BooleanField(default=False, help_text='True if reward is for a civilian informant', verbose_name='Is Civilian Reward')),
                ('officer_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Officer Reviewed At')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Payment Reference')),
                ('claimed_at_station', models.CharField(blank=True, help_text='Police station where civilian claimed reward', max_length=100, verbose_name='Claimed at Station')),
                ('claimed_date', models.DateTimeField(blank=True, null=True, verbose_name='Claim Date')),
                ('verified_by_national_id', models.BooleanField(default=False, help_text='True if recipient verified identity with national ID', verbose_name='Verified by National ID')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='cases.case', verbose_name='Related Case')),
                ('officer_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_officer_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Officer Reviewed By')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_received', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='rewards_rew_status_8a26f9_idx'), models.Index(fields=['recipient', '-created_at'], name='rewards_rew_recipie_ce16aa_idx'), models.Index(fields=['case'], name='rewards_rew_case_id_46d981_idx'), models.Index(fields=['reward_code'], name='rewards_rew_reward__321b69_idx'), models.Index(fields=['is_civilian_reward'], name='rewards_rew_is_civi_afb34c_idx')],
            },
        ),
    ]
