# Generated by Django 6.0 on 2026-02-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='detectivereport',
            name='cases_detec_case_id_f6510b_idx',
        ),
        migrations.RemoveIndex(
            model_name='detectivereport',
            name='cases_detec_status_050095_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidencelink',
            name='cases_evide_case_id_ce7700_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidencelink',
            name='cases_evide_from_co_15cb69_idx',
        ),
        migrations.RemoveIndex(
            model_name='evidencelink',
            name='cases_evide_to_cont_a66629_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='cases_notif_recipie_a104ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='cases_notif_case_id_f14bf9_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='cases_notif_read_at_f29456_idx',
        ),
        migrations.RemoveField(
            model_name='evidencelink',
            name='case',
        ),
        migrations.RemoveField(
            model_name='evidencelink',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='evidencelink',
            name='from_content_type',
        ),
        migrations.RemoveField(
            model_name='evidencelink',
            name='to_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='case',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.DeleteModel(
            name='DetectiveReport',
        ),
        migrations.DeleteModel(
            name='EvidenceLink',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
