# Generated by Django 6.0.2 on 2026-02-27 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='bail_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bail Amount'),
        ),
        migrations.AddField(
            model_name='case',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fine Amount'),
        ),
        migrations.AddField(
            model_name='case',
            name='sergeant_approval',
            field=models.BooleanField(default=False, verbose_name='Sergeant Approval'),
        ),
    ]
